echo "deleting prohibited files..."

cd /
sudo rm *.pdf
sudo rm *.doc
sudo rm *.docx
sudo rm *.xls
sudo rm *.xlsx
sudo rm *.ppt
sudo rm *.pptx
sudo rm *.odt
sudo rm *.ods
sudo rm *.odp
sudo rm *.odg
sudo rm *.odf
sudo rm *.odb
sudo rm *.odc
sudo rm *.odm
sudo rm *.mp3
sudo rm *.mp4
sudo rm *.mov
sudo rm *.gif
sudo rm *.jpg
sudo rm *.jpeg
sudo rm *.png
sudo rm *.wav
sudo rm *.m4a
sudo rm *.ogg
sudo rm *.avi
sudo rm *.flv
sudo rm *.wmv
sudo rm *.mpg
sudo rm *.mpeg
sudo rm *.m4v
sudo rm *.3gp
sudo rm *.3g2
sudo rm *.webm
sudo rm *.tif
sudo rm *.gsm
sudo rm *.flac
sudo rm *.au 
sudo rm *.aiff
sudo rm *.iff
sudo rm *.aif
sudo rm *.vox
sudo rm *.vob
sudo rm *.swf
sudo rm *.srt 
sudo rm *.rm 
sudo rm *.raw
sudo rm *.wma
sudo rm *.m4p
sudo rm *.mid
sudo rm *.ape
sudo rm *.dss
sudo rm *.bat
sudo rm *.ps1
sudo rm *.txt
echo "deleted prohibited files."

