Write-Output "deleting prohibited files..."
Set-Location \
Remove-Item /s /q /f *.mp3
Remove-Item /s /q /f *.mp4
Remove-Item /s /q /f *.mov
Remove-Item /s /q /f *.gif
Remove-Item /s /q /f *.jpg
Remove-Item /s /q /f *.jpeg
Remove-Item /s /q /f *.png
Remove-Item /s /q /f *.wav
Remove-Item /s /q /f *.m4a
Remove-Item /s /q /f *.ogg
Remove-Item /s /q /f *.avi
Remove-Item /s /q /f *.flv
Remove-Item /s /q /f *.wmv
Remove-Item /s /q /f *.webm
Remove-Item /s /q /f *.mpg
Remove-Item /s /q /f *.tif
Remove-Item /s /q /f *.gsm
Remove-Item /s /q /f *.flac
Remove-Item /s /q /f *.au
Remove-Item /s /q /f *.aiff
Remove-Item /s /q /f *.iff
Remove-Item /s /q /f *.aif
Remove-Item /s /q /f *.vox 
Remove-Item /s /q /f *.vob
Remove-Item /s /q /f *.swf
Remove-Item /s /q /f *.srt
Remove-Item /s /q /f *.rm
Remove-Item /s /q /f *.raw
Remove-Item /s /q /f *.wma
Remove-Item /s /q /f *.aac
Remove-Item /s /q /f *.atrac
Remove-Item /s /q /f *.ra
Remove-Item /s /q /f *.ram
Remove-Item /s /q /f *.dss
Remove-Item /s /q /f *.dvf
Remove-Item /s /q /f *.oma
Remove-Item /s /q /f *.atp
Remove-Item /s /q /f *.mid
Remove-Item /s /q /f *.ape
Remove-Item /s /q /f *.ac3
Remove-Item /s /q /f *.m4p
Remove-Item /s /q /f *.midi
Remove-Item /s /q /f *.mp2
Remove-Item /s /q /f *.m3u
Remove-Item /s /q /f *.vqf
Remove-Item /s /q /f *.bmp
Remove-Item /s /q /f *.mpeg3
Remove-Item /s /q /f *.dma
Remove-Item /s /q /f *.wm
Remove-Item /s /q /f *.asx
Remove-Item /s /q /f *.wax
Remove-Item /s /q /f *.wvx
Remove-Item /s /q /f *.wmx
Remove-Item /s /q /f *.dvr-ms
Remove-Item /s /q /f *.wmd
Remove-Item /s /q /f *.mpeg
Remove-Item /s /q /f *.m1v
Remove-Item /s /q /f *.mpa
Remove-Item /s /q /f *.mpe
Remove-Item /s /q /f *.rmi
Remove-Item /s /q /f *.aif
Remove-Item /s /q /f *.aifc
Remove-Item /s /q /f *.snd
Remove-Item /s /q /f *.cda
Remove-Item /s /q /f *.ivf
Remove-Item /s /q /f *.m4v
Remove-Item /s /q /f *.m4pv
Remove-Item /s /q /f *.3g2
Remove-Item /s /q /f *.3gp2
Remove-Item /s /q /f *.3gp
Remove-Item /s /q /f *.adts
Remove-Item /s /q /f *.m2ts
Remove-Item /s /q /f *.hdp
Remove-Item /s /q /f *.wdp
Remove-Item /s /q /f *.aa
Remove-Item /s /q /f *.aax
Remove-Item /s /q /f *.m4b
Remove-Item /s /q /f *.alac
Remove-Item /s /q /f *.sh
Remove-Item /s /q /f *.conf

Write-Output "prohibited files deleted."